### ISSUE TITLE
Copying file showing successful but no file is showing on my destination folder after following same steps. 

### ISSUE THREAD

**Issue by RupeshThakur11** [omkarsm/s3-copier#2]

**Comment by omkarsm** [comment]
Could you please elaborate the issue you are facing.  Like
- Please mention which were the steps you had followed which dint work.
- If possible provide the mock input parameter you had used to make a request. Also state the parameters used were for file/directory copy.

**Comment by omkarsm** [comment]
Hey @RupeshThakur11,
I'm closing down this issue, as i did not get any response from you for a while.
