### ISSUE TITLE
How to Copy buckets from different regions?

### ISSUE THREAD

**Issue by gowthamchna** [omkarsm/s3-copier#3]
How can I perform copy, If the buckets are in different regions?

`var param = {
        region: "ANY REGION",			//	AWS region
        secretAccessKey: "*****************",	//	AWS secret access key
        accessKeyId: "*********"		//	AWS access key ID
    };`

**Comment by omkarsm** [comment]
@littleboy1103 

Multi-region bucket copy is not supported yet.
But this would be a new feature which we will be adding in upcoming build.
Thanks for the feedback :)
